import lexerparser as lexer
lexed = lexer.lexer("func _main { printc 2; printa; };")
print(lexed)
parsed = lexer.parser(lexed)
print(parsed)
compiled = lexer.compile(parsed)
print(compiled)
f = open("compilied.txt", "w")
f.write(compiled)
f.close()